language: node_js
node_js:
  - '10'
cache: npm
install:
    - npm install
before_script:
  - npm install
  - npm rebuild

script: 
  - npm run build

cache:
  directories:
    - "node_modules"

jobs:
    include:
        - stage: Release to GitHub
          deploy: 
            provider: releases
            api_key: $GITHUB_TOKEN
            file_glob: true
            file: build/*
            skip_cleanup: true
            on:
              tags: true
        - stage: Release to NPM
          deploy:
            provider: npm
            email: $NPM_EMAIL
            api_key: $NPM_TOKEN
            file_glob: true
            file: build/*
            skip_cleanup: true
            on:
              tags: true
 branches:
    only:
        - master
        - /^v[0-9]+.*$/