language: node_js
node_js:
  - "node"

before_script:
  - npm install
  - npm rebuild

script: 
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true