language: node_js
node_js:
  - 'node'
cache: npm
before_script:
  - npm install
  - npm rebuild

script: 
  - npm run build

cache:
  directories:
    - "node_modules"

jobs:
    include:
        - stage: Release to NPM
          deploy:
            provider: npm
            email: $NPM_EMAIL
            api_key: $NPM_TOKEN
            file_glob: true
            file: build/*
            skip_cleanup: true
            on:
              tags: true
branches:
    only:
        - /^v[0-9]+.*$/